### ISSUE TITLE
Does not work on Plone 6

### ISSUE THREAD

**Issue by Rudd-O** [plone/plone.formwidget.captcha#11]
```
Dec 26 04:11:47 ring2-plonedev frontend[180401]: 2021-12-26 04:11:47,729 ERROR   [plone.autoinclude.loader:40][MainThread] Could not import plone.formwidget.captcha.
Dec 26 04:11:47 ring2-plonedev frontend[180401]: Traceback (most recent call last):
Dec 26 04:11:47 ring2-plonedev frontend[180401]:   File "/home/user/optplone/buildout-cache/eggs/cp38/plone.autoinclude-1.0.0a3-py3.8.egg/plone/autoinclude/loader.py", line 36, in load_z3c_packages
Dec 26 04:11:47 ring2-plonedev frontend[180401]:     dist = importlib.import_module(module_name)
Dec 26 04:11:47 ring2-plonedev frontend[180401]:   File "/home/user/optpython/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
Dec 26 04:11:47 ring2-plonedev frontend[180401]:     return _bootstrap._gcd_import(name[level:], package, level)
Dec 26 04:11:47 ring2-plonedev frontend[180401]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Dec 26 04:11:47 ring2-plonedev frontend[180401]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Dec 26 04:11:47 ring2-plonedev frontend[180401]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Dec 26 04:11:47 ring2-plonedev frontend[180401]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Dec 26 04:11:47 ring2-plonedev frontend[180401]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
Dec 26 04:11:47 ring2-plonedev frontend[180401]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Dec 26 04:11:47 ring2-plonedev frontend[180401]:   File "/home/user/optplone/buildout-cache/eggs/cp38/plone.formwidget.captcha-1.0.3-py3.8.egg/plone/formwidget/captcha/__init__.py", line 4, in <module>
Dec 26 04:11:47 ring2-plonedev frontend[180401]:     from plone.formwidget.captcha.widget import CaptchaWidget
Dec 26 04:11:47 ring2-plonedev frontend[180401]:   File "/home/user/optplone/buildout-cache/eggs/cp38/plone.formwidget.captcha-1.0.3-py3.8.egg/plone/formwidget/captcha/widget.py", line 10, in <module>
Dec 26 04:11:47 ring2-plonedev frontend[180401]:     from interfaces import ICaptchaWidget
Dec 26 04:11:47 ring2-plonedev frontend[180401]: ModuleNotFoundError: No module named 'interfaces'
```

**Comment by Rudd-O** [comment]
Additional traceback when the _obvious_ import problem is fixed:

```
Dec 26 04:14:12 ring2-plonedev frontend[180662]: Traceback (most recent call last):
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optplone/buildout-cache/eggs/cp38/zope.configuration-4.4.0-py3.8.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     self.context.end()
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optplone/buildout-cache/eggs/cp38/zope.configuration-4.4.0-py3.8.egg/zope/configuration/config.py", line 704, in end
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     self.stack.pop().finish()
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optplone/buildout-cache/eggs/cp38/zope.configuration-4.4.0-py3.8.egg/zope/configuration/config.py", line 869, in finish
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     actions = self.handler(context, **args)
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optplone/buildout-cache/eggs/cp38/plone.autoinclude-1.0.0a3-py3.8.egg/plone/autoinclude/zcml.py", line 37, in includePluginsDirective
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     dists = loader.load_packages(target)
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optplone/buildout-cache/eggs/cp38/plone.autoinclude-1.0.0a3-py3.8.egg/plone/autoinclude/loader.py", line 107, in load_packages
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     z3c_dists = load_z3c_packages(target=target)
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optplone/buildout-cache/eggs/cp38/plone.autoinclude-1.0.0a3-py3.8.egg/plone/autoinclude/loader.py", line 36, in load_z3c_packages
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     dist = importlib.import_module(module_name)
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optpython/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     return _bootstrap._gcd_import(name[level:], package, level)
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optplone/buildout-cache/eggs/cp38/plone.formwidget.captcha-1.0.3-py3.8.egg/plone/formwidget/captcha/__init__.py", line 4, in <module>
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     from plone.formwidget.captcha.widget import CaptchaWidget
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optplone/buildout-cache/eggs/cp38/plone.formwidget.captcha-1.0.3-py3.8.egg/plone/formwidget/captcha/widget.py", line 10, in <module>
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     class CaptchaWidget(text.TextWidget):
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optplone/buildout-cache/eggs/cp38/plone.formwidget.captcha-1.0.3-py3.8.egg/plone/formwidget/captcha/widget.py", line 14, in CaptchaWidget
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     zope.interface.implementsOnly(ICaptchaWidget)
Dec 26 04:14:12 ring2-plonedev frontend[180662]:   File "/home/user/optplone/buildout-cache/eggs/cp38/zope.interface-5.4.0-py3.8-linux-x86_64.egg/zope/interface/declarations.py", line 806, in implementsOnly
Dec 26 04:14:12 ring2-plonedev frontend[180662]:     raise TypeError(_ADVICE_ERROR % 'implementer_only')
Dec 26 04:14:12 ring2-plonedev frontend[180662]: TypeError: Class advice impossible in Python3.  Use the @implementer_only class decorator instead.
```

**Comment by Rudd-O** [comment]
When the `implementsOnly` issue is fixed,

```
Dec 26 04:16:24 ring2-plonedev frontend[181033]:     __import__(mname)
Dec 26 04:16:24 ring2-plonedev frontend[181033]:   File "/home/user/optplone/buildout-cache/eggs/cp38/plone.formwidget.captcha-1.0.3-py3.8.egg/plone/formwidget/captcha/browser/captcha.py", line 14, in <module>
Dec 26 04:16:24 ring2-plonedev frontend[181033]:     from skimpyGimpy import skimpyAPI
Dec 26 04:16:24 ring2-plonedev frontend[181033]:   File "/home/user/optplone/buildout-cache/eggs/cp38/skimpyGimpy-1.4-py3.8.egg/skimpyGimpy/skimpyAPI.py", line 38
Dec 26 04:16:24 ring2-plonedev frontend[181033]:     raise ValueError, "hex color specifications must have 6 hex digits: "+repr(s)
Dec 26 04:16:24 ring2-plonedev frontend[181033]:                     ^
```

This package is totally hosed and will not work with Python 3.

**Comment by Rudd-O** [comment]
Fixed `widget.py` code:

```
from Acquisition import aq_inner
from z3c.form import widget
from z3c.form.browser import text
import zope.component
from zope.interface.declarations import implementer_only

from .interfaces import ICaptchaWidget


@implementer_only(ICaptchaWidget)
class CaptchaWidget(text.TextWidget):
    maxlength = 7
    size = 8

    def captchaImage(self):
        self.captcha = zope.component.getMultiAdapter((aq_inner(self.context), 
                                                       self.request), 
                                                       name='captcha')
        return self.captcha.image_tag()

    def captchaAudio(self):
        self.captcha = zope.component.getMultiAdapter((aq_inner(self.context), 
                                                       self.request), 
                                                       name='captcha')
        return self.captcha.audio_url()

def CaptchaFieldWidget(field, request):
    """IFieldWidget factory for CaptchaWidget."""
    return widget.FieldWidget(field, CaptchaWidget(request))
```

**Comment by Rudd-O** [comment]
https://pypi.org/project/skimpyGimpy/ has not had a release in many years.  It's not Python 3 compatible.

Suggestion: fork it, fix it, and then include it directly here.

**Comment by Rudd-O** [comment]
These appear to be the maintainers: https://github.com/syslabcom/skimpyGimpy

It's not clear that they want to release to PyPI a PY3 version that works.
